### ISSUE TITLE
Parallel Bootstrap Issues.

### ISSUE THREAD

**Issue by dmlb2000** [chef-cookbooks/ssh_known_hosts#50]
Seems like if there are two knife bootstraps going on at the same time the one that includes the ssh_known_hosts recipe seems to produce this error and can't converge until the other one is complete. In fact all hosts seem to produce this error until the bootstrapped node completes.

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/msc_core/recipes/msc_auth.rb
================================================================================

ArgumentError
-------------
You must supply a name when declaring a ssh_known_hosts_entry resource

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/ssh_known_hosts/recipes/default.rb:85:in `block in from_file'
  /var/chef/cache/cookbooks/ssh_known_hosts/recipes/default.rb:77:in `each'
  /var/chef/cache/cookbooks/ssh_known_hosts/recipes/default.rb:77:in `from_file'
  /var/chef/cache/cookbooks/msc/recipes/sshd.rb:17:in `from_file'
  /var/chef/cache/cookbooks/msc_core/recipes/msc_auth.rb:2:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/ssh_known_hosts/recipes/default.rb:

 78:    unless host['key'].nil?
 79:      # The key was specified, so use it
 80:      ssh_known_hosts_entry host['fqdn'] do
 81:        key host['key']
 82:      end
 83:    else
 84:      # No key specified, so have known_host perform a DNS lookup
 85>>     ssh_known_hosts_entry host['fqdn']
 86:    end
 87:  end
 88:

```

All we are doing in our recipe is the following.

```
include_recipe 'ssh_known_hosts'
```

**Comment by lamont-granquist** [comment]
that probably doesn't have anything to do with `parallel` bootstraps, and has more to do with running this cookbook on one node (no matter what state that node is in) while another node is bootstrapping and has not fully run but has a node object without an fqdn or other ohai information (e.g. validatorless boostrapping where the node is created first).

**Comment by lamont-granquist** [comment]
there's an `unless host['fqdn'].nil?` check on that line now, this issue is likely fixed.
