### ISSUE TITLE
Remove dependency on deprecated cookbook partial_search

### ISSUE THREAD

**Issue by iennae** [chef-cookbooks/ssh_known_hosts#55]
### Cookbook version
Latest 2.0.0

### Chef-client version
Not Relevant

### Platform Details
All AFAIK.

### Scenario:
When investigating a PR, ran into this error

<details>
         Chef::REST is deprecated. Please use Chef::ServerAPI, or investigate Ridley or ChefAPI. at 1 location:
           - /tmp/kitchen/cache/cookbooks/partial_search/libraries/partial_search.rb:35:in `new'
</details>
, and looked up the cookbook partial_search info, and discovered it's deprecated.

### Steps to Reproduce:
kitchen converge INSTANCE

### Expected Result:
No errors. 

### Actual Result:
<details>
         Chef::REST is deprecated. Please use Chef::ServerAPI, or investigate Ridley or ChefAPI. at 1 location:
           - /tmp/kitchen/cache/cookbooks/partial_search/libraries/partial_search.rb:35:in `new'
</details>

**Comment by iennae** [comment]
Resolved with version 3.0.0 of this cookbook.
