### ISSUE TITLE
:flush action does not work as expected (Cannot find a resource matching template)

### ISSUE THREAD

**Issue by rmldsky** [chef-cookbooks/ssh_known_hosts#89]
### Cookbook version
`6.1.3`

### Chef-client version
`12.22.4`

### Scenario:
```
 Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/mycookbook/recipes/_deploy.rb

      5: ssh_known_hosts_entry 'github.com' do
      6:   action :flush
      7: end
      8:
```

### Expected Result:
Adds entry during runtime.

### Actual Result:
```
  * ssh_known_hosts_entry[github.com] action flush

   ================================================================================
    Error executing action `flush` on resource 'ssh_known_hosts_entry[github.com]'
    ================================================================================

    Chef::Exceptions::ResourceNotFound
    ----------------------------------
    Cannot find a resource matching template[update ssh known hosts file /etc/ssh/ssh_known_hosts] (did you define it first?)

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/ssh_known_hosts/resources/entry.rb:78:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/ssh_known_hosts/resources/entry.rb:76:in `block in class_from_file'
```

Resource expands to:
```
   ssh_known_hosts_entry("github.com") do
      action [:flush]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :ssh_known_hosts_entry
      cookbook_name "mycookbook"
      recipe_name "_deploy"
      file_location "/etc/ssh/ssh_known_hosts"
      host "github.com"
      key_type "rsa"
      mode "0644"
      owner "root"
      group "root"
    end
```

When I just use `ssh_known_hosts_entry 'github.com'` entry is added to `/etc/ssh/ssh_known_hosts` but not available during runtime. When changed declaration to use `:flush` the above error happens.

**Comment by rmldsky** [comment]
Ah my bad, didn't understand documentation at first.
